-- V1__init_schema.sql
-- Schema definition for Aiswarya Swayam Sahaya Sangham Financial Ledger Backend

-- 1. Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'MEMBER')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Members Table
CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE REFERENCES users(id) ON DELETE RESTRICT,
    member_number VARCHAR(20) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(15) UNIQUE,
    address TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    joining_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Member Accounts Table (Current Balances per Category per Member)
CREATE TABLE member_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
    account_type VARCHAR(30) NOT NULL CHECK (
        account_type IN (
            'LOAN',
            'DEPOSIT',
            'FINE',
            'FINANCIAL_AID',
            'MONTHLY_CONTRIBUTION',
            'INTEREST'
        )
    ),
    current_balance NUMERIC(15, 2) NOT NULL DEFAULT 0.00 CHECK (current_balance >= 0.00),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_member_account UNIQUE (member_id, account_type)
);

-- 4. Meetings Table
CREATE TABLE meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_number INT NOT NULL UNIQUE,
    meeting_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED' CHECK (
        status IN ('SCHEDULED', 'OPEN', 'COMPLETED', 'CANCELLED')
    ),
    interest_period VARCHAR(7) NOT NULL,
    is_first_meeting_of_month BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    opened_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_by BIGINT REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_meetings_date ON meetings(meeting_date);
CREATE INDEX idx_meetings_period ON meetings(interest_period, is_first_meeting_of_month);

-- 5. Meeting Members Processing Table
CREATE TABLE meeting_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
    processing_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (
        processing_status IN ('PENDING', 'COMPLETED')
    ),
    processed_at TIMESTAMP WITH TIME ZONE,
    processed_by BIGINT REFERENCES users(id),
    CONSTRAINT uk_meeting_member UNIQUE (meeting_id, member_id)
);

CREATE INDEX idx_meeting_members_status ON meeting_members(meeting_id, processing_status);

-- 6. Financial Transactions Table (Append-Only Ledger)
CREATE TABLE financial_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
    account_type VARCHAR(30) NOT NULL CHECK (
        account_type IN (
            'LOAN',
            'DEPOSIT',
            'FINE',
            'FINANCIAL_AID',
            'MONTHLY_CONTRIBUTION',
            'INTEREST'
        )
    ),
    transaction_type VARCHAR(30) NOT NULL CHECK (
        transaction_type IN (
            'INITIAL_BALANCE',
            'LOAN_ISSUED',
            'ADDITION',
            'REPAYMENT',
            'INTEREST_APPLIED',
            'ADJUSTMENT',
            'REVERSAL'
        )
    ),
    amount NUMERIC(15, 2) NOT NULL CHECK (amount > 0.00),
    balance_before NUMERIC(15, 2) NOT NULL CHECK (balance_before >= 0.00),
    balance_after NUMERIC(15, 2) NOT NULL CHECK (balance_after >= 0.00),
    meeting_id BIGINT REFERENCES meetings(id) ON DELETE RESTRICT,
    reference_type VARCHAR(50),
    reference_id BIGINT,
    description TEXT,
    idempotency_key VARCHAR(100),
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tx_member_account ON financial_transactions(member_id, account_type);
CREATE INDEX idx_tx_meeting ON financial_transactions(meeting_id);
CREATE INDEX idx_tx_idempotency ON financial_transactions(idempotency_key);

-- 7. Interest Calculations Table (Per Member Per Interest Period)
CREATE TABLE interest_calculations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
    interest_period VARCHAR(7) NOT NULL,
    meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE RESTRICT,
    loan_balance_used NUMERIC(15, 2) NOT NULL CHECK (loan_balance_used >= 0.00),
    interest_rate NUMERIC(5, 4) NOT NULL DEFAULT 0.0100,
    interest_amount NUMERIC(15, 2) NOT NULL CHECK (interest_amount >= 0.00),
    status VARCHAR(20) NOT NULL DEFAULT 'CALCULATED' CHECK (
        status IN ('PENDING', 'CALCULATED', 'PARTIALLY_PAID', 'PAID')
    ),
    calculated_by BIGINT NOT NULL REFERENCES users(id),
    calculated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_member_interest_period UNIQUE (member_id, interest_period)
);

CREATE INDEX idx_interest_member_period ON interest_calculations(member_id, interest_period);

-- 8. Idempotency Records Table
CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(100) NOT NULL UNIQUE,
    request_path VARCHAR(255) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    response_code INT NOT NULL,
    response_body TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 9. Audit Logs Table
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    action VARCHAR(100) NOT NULL,
    entity_name VARCHAR(50) NOT NULL,
    entity_id BIGINT,
    details TEXT,
    ip_address VARCHAR(45),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
