CREATE TABLE IF NOT EXISTS special_loan_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Drop legacy unique constraint on (member_id, account_type) to support multiple special loan accounts per member
ALTER TABLE member_accounts DROP CONSTRAINT IF EXISTS uk_member_account;

-- Drop account_type check constraints if present (PostgreSQL & H2)
ALTER TABLE member_accounts DROP CONSTRAINT IF EXISTS CONSTRAINT_B6C;
ALTER TABLE member_accounts DROP CONSTRAINT IF EXISTS member_accounts_account_type_check;

ALTER TABLE financial_transactions DROP CONSTRAINT IF EXISTS CONSTRAINT_DF0;
ALTER TABLE financial_transactions DROP CONSTRAINT IF EXISTS financial_transactions_account_type_check;

-- Add special_loan_type_id foreign keys if not present
ALTER TABLE member_accounts ADD COLUMN IF NOT EXISTS special_loan_type_id BIGINT;
ALTER TABLE member_accounts DROP CONSTRAINT IF EXISTS fk_member_account_special_loan_type;
ALTER TABLE member_accounts ADD CONSTRAINT fk_member_account_special_loan_type FOREIGN KEY (special_loan_type_id) REFERENCES special_loan_types(id);

ALTER TABLE financial_transactions ADD COLUMN IF NOT EXISTS special_loan_type_id BIGINT;
ALTER TABLE financial_transactions DROP CONSTRAINT IF EXISTS fk_financial_tx_special_loan_type;
ALTER TABLE financial_transactions ADD CONSTRAINT fk_financial_tx_special_loan_type FOREIGN KEY (special_loan_type_id) REFERENCES special_loan_types(id);

-- Seed default Special Loan Types if not present
INSERT INTO special_loan_types (name, description, is_active)
SELECT 'ലോട്ടറി (Lottery)', 'Advance loan for purchasing lottery tickets', TRUE
WHERE NOT EXISTS (SELECT 1 FROM special_loan_types WHERE name = 'ലോട്ടറി (Lottery)');

INSERT INTO special_loan_types (name, description, is_active)
SELECT 'പുസ്തകം (Book)', 'Loan for purchasing books and stationery', TRUE
WHERE NOT EXISTS (SELECT 1 FROM special_loan_types WHERE name = 'പുസ്തകം (Book)');
