CREATE TABLE IF NOT EXISTS member_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS member_group_members (
    group_id BIGINT NOT NULL REFERENCES member_groups(id) ON DELETE CASCADE,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, member_id)
);

CREATE TABLE IF NOT EXISTS group_loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT REFERENCES member_groups(id) ON DELETE SET NULL,
    account_type VARCHAR(30) NOT NULL,
    special_loan_type_id BIGINT REFERENCES special_loan_types(id) ON DELETE SET NULL,
    total_amount NUMERIC(15, 2) NOT NULL CHECK (total_amount > 0.00),
    per_member_amount NUMERIC(15, 2) NOT NULL CHECK (per_member_amount > 0.00),
    member_count INT NOT NULL CHECK (member_count > 0),
    notes TEXT,
    transaction_date DATE NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_group_loans_group ON group_loans(group_id);
CREATE INDEX IF NOT EXISTS idx_group_loans_date ON group_loans(transaction_date);
