CREATE TABLE IF NOT EXISTS expense_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_type_id BIGINT NOT NULL REFERENCES expense_types(id),
    amount NUMERIC(15, 2) NOT NULL CHECK (amount > 0.00),
    expense_date DATE NOT NULL,
    description TEXT,
    meeting_id BIGINT REFERENCES meetings(id) ON DELETE SET NULL,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO expense_types (name, description) VALUES
('Meeting Refreshment', 'Tea, snacks, refreshments during meetings'),
('Stationery & Supplies', 'Register books, pens, printouts'),
('Event & Function', 'Group events and celebrations'),
('Miscellaneous Expense', 'Other operational group expenses');
